version: '3.4'

# networks:
#   mm-net:

x-environment:
  &default-env
  CONFIGURATION_SERVICE_URL: http://config:8080
  STS_URL: http:\/\/champagne.stackstate.io:7077\/stsAgent\/
#  STS_URL: http:\/\/192.168.178.248:7077\/stsAgent\/

services:
  # Microservices
  mad-1:
    image: "mad-service:latest"
    environment:
      << : *default-env
      SERVICE: mad-1
      DEPENDENCIES: mad-2:8080|0.75,mad-3:8080|0.25
      LATENCY: 5000
      ERROR_RATE: 0.01
    # NOTE: only entrypoint exposes port
    ports:
      - "8080:8080"
    links:
      - mad-2
  mad-2:
    image: "mad-service:latest"
    environment:
      << : *default-env
      SERVICE: mad-2
      LATENCY: 5000
      ERROR_RATE: 0.00
    ports:
      - "8081:8080"
  mad-3:
    image: "mad-service:latest"
    environment:
      << : *default-env
      SERVICE: mad-3
      LATENCY: 2000
      ERROR_RATE: 0.01
    ports:
      - "8082:8080"




  # Infrastructure
  config:
    image: "config-service:latest"
    ports:
      - "9090:8080"
    volumes:
      - ./config:/config
  load-generator:
    image: "load-generator-tsung:latest"
    environment:
      TAGS: mm,load-generator
    depends_on:
      - mad-1
      - mad-2
      - mad-3
    volumes:
      - "./log:/root/.tsung/log"
    links:
      - "mad-1:entry-1"
    entrypoint:
      - tsung
      - -w
      - "60"
      - start
